import type { ShoppingHistoryInput } from "@/types";

export const INITIAL_SHOPPING_HISTORY: ShoppingHistoryInput = {
  date: "2026-08-05",
  total: 551.98,
  items: [
    { name: "Suco tang", qty: 6, price: 0.99 },
    { name: "Pipoca micro", qty: 4, price: 4.99 },
    { name: "Tapioca 1kg", qty: 1, price: 7.99 },
    { name: "Lâmpada 20w", qty: 1, price: 12.9 },
    { name: "Saco 5kg", qty: 1, price: 11.9 },
    { name: "Papel toalha", qty: 1, price: 5.99 },
    { name: "Amaciante 2lt", qty: 1, price: 11.9 },
    { name: "Detergente líquido 500ml", qty: 2, price: 2.89 },
    { name: "Assolam aço", qty: 1, price: 2.19 },
    { name: "Pastilha sanitário", qty: 1, price: 8.29 },
    { name: "Difusor de aroma", qty: 1, price: 17.89 },
    { name: "Loção hidratante 200ml", qty: 1, price: 16.89 },
    { name: "Sacola hig", qty: 1, price: 9.9 },
    { name: "Cond 200ml", qty: 1, price: 18.89 },
    { name: "Papel hig 12rolos", qty: 1, price: 13.89 },
    { name: "Óleo de soja", qty: 1, price: 6.59 },
    { name: "Salgadinhos yoki", qty: 4, price: 1.99 },
    { name: "Biscoito tucs", qty: 2, price: 2.29 },
    { name: "Café do ponto 500g", qty: 1, price: 25 },
    { name: "Fermento 100g", qty: 1, price: 4.99 },
    { name: "Milho verde 200g", qty: 2, price: 2.59 },
    { name: "Tempero galinha", qty: 1, price: 2.95 },
    { name: "Queijo parmesão ralado", qty: 2, price: 4.49 },
    { name: "Passata", qty: 2, price: 3.49 },
    { name: "Macarrão dallas 500g", qty: 1, price: 4.49 },
    { name: "Toddy 370g", qty: 1, price: 9.98 },
    { name: "Leite pó", qty: 1, price: 18.89 },
    { name: "Granola jasmine", qty: 1, price: 10.9 },
    { name: "Leite longa vida 1lt", qty: 2, price: 5.29 },
    { name: "Chipa", qty: 4, price: 1.99 },
    { name: "Requeijão 400g", qty: 1, price: 17.99 },
    { name: "Picanha", qty: 1, price: 35.68 },
    { name: "Mussarela fatiado", qty: 2, price: 8.59 },
    { name: "Mandioca", qty: 1, price: 10.99 },
    { name: "Presunto fatiado", qty: 1, price: 6.98 },
    { name: "Filé mignon suíno", qty: 1, price: 44.81 },
    { name: "Filezinho sassami", qty: 1, price: 16.9 },
    { name: "Coxinha da asa", qty: 1, price: 9.29 },
    { name: "Pão bauducco", qty: 1, price: 8.09 },
    { name: "Posta tilápia 800g", qty: 1, price: 23.89 },
    { name: "Pão de queijo 1kg", qty: 1, price: 11.99 },
    { name: "Tekitos 1kg", qty: 1, price: 22.9 },
    { name: "Iog frutap 1,15kg", qty: 1, price: 13.69 },
    { name: "Açúcar 2kg", qty: 1, price: 5.29 },
  ],
};
